services:
  manhwa-front:
    image: manhwa-front
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.manhwa-front.rule=Host(`manhwa.abrines.fr`)
      - traefik.http.routers.manhwa-front.entrypoints=websecure
      - traefik.http.routers.manhwa-front.tls=true
      - traefik.http.services.manhwa-front.loadbalancer.server.port=80